bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

bind r source-file ~/.tmux.conf

bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

set -g mouse on

set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin "tmux-plugins/tmux-yank"

set -g @plugin 'dracula/tmux'
set -g @dracula-colors "
white='#fcfcfa'
gray='#403e41'
dark_gray='#2d2a2e'
light_purple='#ab9df2'
dark_purple='#5b595c'
cyan='#78dce8'
green='#a9dc76'
orange='#fc9867'
red='#ff6188'
pink='#ff79c6'
yellow='#ffd866'
"
set -g @dracula-show-flags true
set -g @dracula-show-powerline true
set -g @dracula-show-left-icon "#S"
set -g @dracula-plugins "cpu-usage ram-usage time"
set -g @dracula-cpu-usage-label ""
set -g @dracula-ram-usage-label ""
set -g @dracula-show-timezone false

run '~/.tmux/plugins/tpm/tpm'
