set -g default-terminal "tmux-256color"
set -as terminal-features ",*:RGB"
set -g mouse on

bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

bind r source-file ~/.tmux.conf

bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

bind -n M-S-Left previous-window
bind -n M-S-Right next-window

bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin "tmux-plugins/tmux-yank"

set -g @plugin 'dracula/tmux'
set -g @dracula-colors "
white='#fcfcfa'
gray='#403e41'
dark_gray='#2d2a2e'
light_purple='#ab9df2'
dark_purple='#5b595c'
cyan='#78dce8'
green='#a9dc76'
orange='#fc9867'
red='#ff6188'
pink='#ff79c6'
yellow='#ffd866'
"
set -g @dracula-show-flags true
set -g @dracula-show-powerline true
set -g @dracula-show-left-icon "#S"
set -g @dracula-border-contrast true
set -g @dracula-plugins "cpu-usage ram-usage time"
set -g @dracula-cpu-usage-label ""
set -g @dracula-ram-usage-label ""
set -g @dracula-show-timezone false

unbind t
bind t command-prompt -p "Pane title:" "select-pane -T '%%'"
set -g pane-border-status top
set -g pane-border-format "#{?pane_active,#[fg=#ab9df2 bold],#[fg=#5b595c]} #P #{pane_title} | #{?pane_active,#[fg=#78dce8 bold],#[fg=#5b595c]}#{pane_current_command} "

run '~/.tmux/plugins/tpm/tpm'
